language: python
python:
  - "3.6"
sudo: required

before_install:
  - |
    if [ "$TRAVIS_BRANCH" != "$SOURCE_BRANCH" ]; then
      travis_terminate;
    fi

install:
  - sudo apt-get install texlive
  - pip install readme2tex

script: 
  - ./texify
  - mv .$TARGET_BRANCH.gitignore .gitignore
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  target-branch: $TARGET_BRANCH
  on:
    all_branches: true
